import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../data/datasources/supabase_match_event_repository.dart';
import '../data/models/match_event.dart';

/// Repository provider for match events
final matchEventRepositoryProvider = Provider<SupabaseMatchEventRepository>((ref) {
  return SupabaseMatchEventRepository(Supabase.instance.client);
});

/// Get events for a match
final matchEventsProvider =
    FutureProvider.family<List<MatchEvent>, String>((ref, matchId) async {
  final repo = ref.watch(matchEventRepositoryProvider);
  return await repo.getEventsByMatch(matchId);
});

/// Stream of events for a match (real-time updates)
final matchEventsStreamProvider =
    StreamProvider.family<List<MatchEvent>, String>((ref, matchId) {
  final repo = ref.watch(matchEventRepositoryProvider);
  return repo.subscribeToMatchEvents(matchId);
});

/// Add goal event request
class AddGoalRequest {
  final String matchId;
  final String teamId;
  final String? playerName;
  final int? minute;
  final MatchEventType eventType;

  AddGoalRequest({
    required this.matchId,
    required this.teamId,
    this.playerName,
    this.minute,
    this.eventType = MatchEventType.goal,
  });
}

/// Add goal event provider
final addGoalEventProvider =
    FutureProvider.family<MatchEvent, AddGoalRequest>((ref, request) async {
  final repo = ref.watch(matchEventRepositoryProvider);
  
  final event = MatchEvent(
    id: '', // Will be generated by DB
    matchId: request.matchId,
    teamId: request.teamId,
    eventType: request.eventType,
    playerName: request.playerName,
    minute: request.minute,
  );
  
  final created = await repo.createEvent(event);
  ref.invalidate(matchEventsProvider(request.matchId));
  return created;
});

/// Delete goal event provider
final deleteGoalEventProvider =
    FutureProvider.family<void, ({String eventId, String matchId})>((ref, request) async {
  final repo = ref.watch(matchEventRepositoryProvider);
  await repo.deleteEvent(request.eventId);
  ref.invalidate(matchEventsProvider(request.matchId));
});
