import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../data/models/organisation.dart';
import '../../../providers/auth_providers.dart';
import '../../../providers/organisation_providers.dart';
import '../../widgets/common/loading_error_widgets.dart';

/// Form for creating/editing organisations
class OrganisationFormScreen extends ConsumerStatefulWidget {
  final String? organisationId;

  const OrganisationFormScreen({
    super.key,
    this.organisationId,
  });

  @override
  ConsumerState<OrganisationFormScreen> createState() => _OrganisationFormScreenState();
}

class _OrganisationFormScreenState extends ConsumerState<OrganisationFormScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _logoUrlController = TextEditingController();
  final _descriptionController = TextEditingController();
  
  bool _isLoading = false;
  bool _isInitialized = false;

  bool get isEditing => widget.organisationId != null;

  @override
  void dispose() {
    _nameController.dispose();
    _logoUrlController.dispose();
    _descriptionController.dispose();
    super.dispose();
  }

  void _initializeForm(Organisation org) {
    if (_isInitialized) return;
    _nameController.text = org.name;
    _logoUrlController.text = org.logoUrl ?? '';
    _descriptionController.text = org.description ?? '';
    _isInitialized = true;
  }

  Future<void> _handleSubmit() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isLoading = true);

    try {
      final authState = ref.read(authNotifierProvider);
      final user = authState.value;
      
      if (user == null) {
        throw Exception('User not authenticated');
      }

      if (isEditing) {
        final existing = ref.read(organisationByIdProvider(widget.organisationId!)).value;
        if (existing == null) throw Exception('Organisation not found');

        final updated = existing.copyWith(
          name: _nameController.text.trim(),
          logoUrl: _logoUrlController.text.trim().isEmpty ? null : _logoUrlController.text.trim(),
          description: _descriptionController.text.trim().isEmpty ? null : _descriptionController.text.trim(),
        );
        await ref.read(updateOrganisationProvider(updated).future);
      } else {
        final newOrg = Organisation(
          id: '', // Will be generated by Supabase
          name: _nameController.text.trim(),
          ownerId: user.id,
          ownerEmail: user.email,
          logoUrl: _logoUrlController.text.trim().isEmpty ? null : _logoUrlController.text.trim(),
          description: _descriptionController.text.trim().isEmpty ? null : _descriptionController.text.trim(),
          createdAt: DateTime.now(),
          updatedAt: DateTime.now(),
        );
        await ref.read(createOrganisationProvider(newOrg).future);
      }

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(isEditing ? 'Organisation updated' : 'Organisation created'),
            backgroundColor: Theme.of(context).colorScheme.primary,
          ),
        );
        context.go('/admin');
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error: $e'),
            backgroundColor: Theme.of(context).colorScheme.error,
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  Future<void> _handleDelete() async {
    final confirmed = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Delete Organisation'),
        content: const Text(
          'Are you sure you want to delete this organisation? '
          'This will also delete all associated tournaments, teams, and matches.',
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context, false),
            child: const Text('Cancel'),
          ),
          FilledButton(
            onPressed: () => Navigator.pop(context, true),
            style: FilledButton.styleFrom(
              backgroundColor: Theme.of(context).colorScheme.error,
            ),
            child: const Text('Delete'),
          ),
        ],
      ),
    );

    if (confirmed != true || !mounted) return;

    setState(() => _isLoading = true);

    try {
      await ref.read(deleteOrganisationProvider(widget.organisationId!).future);
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Organisation deleted')),
        );
        context.go('/admin');
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error: $e'),
            backgroundColor: Theme.of(context).colorScheme.error,
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(isEditing ? 'Edit Organisation' : 'New Organisation'),
        leading: IconButton(
          icon: const Icon(Icons.close),
          onPressed: () => context.go('/admin'),
        ),
        actions: [
          if (isEditing)
            IconButton(
              icon: const Icon(Icons.delete),
              tooltip: 'Delete',
              onPressed: _isLoading ? null : _handleDelete,
            ),
        ],
      ),
      body: isEditing
        ? _buildEditingForm()
        : _buildForm(),
    );
  }

  Widget _buildEditingForm() {
    final orgAsync = ref.watch(organisationByIdProvider(widget.organisationId!));

    return orgAsync.when(
      data: (org) {
        if (org == null) {
          return const Center(child: Text('Organisation not found'));
        }
        _initializeForm(org);
        return _buildForm();
      },
      loading: () => const LoadingWidget(),
      error: (e, _) => AppErrorWidget(
        message: e.toString(),
        onRetry: () => ref.invalidate(organisationByIdProvider(widget.organisationId!)),
      ),
    );
  }

  Widget _buildForm() {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(24),
      child: Form(
        key: _formKey,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            // Name Field
            TextFormField(
              controller: _nameController,
              enabled: !_isLoading,
              textInputAction: TextInputAction.next,
              decoration: const InputDecoration(
                labelText: 'Organisation Name *',
                hintText: 'e.g., Ramadan Football League',
                prefixIcon: Icon(Icons.business),
              ),
              validator: (value) {
                if (value == null || value.trim().isEmpty) {
                  return 'Please enter an organisation name';
                }
                return null;
              },
            ),
            const SizedBox(height: 16),

            // Logo URL Field
            TextFormField(
              controller: _logoUrlController,
              enabled: !_isLoading,
              keyboardType: TextInputType.url,
              textInputAction: TextInputAction.next,
              decoration: const InputDecoration(
                labelText: 'Logo URL',
                hintText: 'https://example.com/logo.png',
                prefixIcon: Icon(Icons.image),
              ),
              validator: (value) {
                if (value != null && value.isNotEmpty) {
                  final uri = Uri.tryParse(value);
                  if (uri == null || !uri.hasScheme) {
                    return 'Please enter a valid URL';
                  }
                }
                return null;
              },
            ),
            const SizedBox(height: 16),

            // Description Field
            TextFormField(
              controller: _descriptionController,
              enabled: !_isLoading,
              maxLines: 3,
              textInputAction: TextInputAction.done,
              decoration: const InputDecoration(
                labelText: 'Description',
                hintText: 'Brief description of your organisation',
                prefixIcon: Icon(Icons.description_outlined),
                alignLabelWithHint: true,
              ),
            ),
            const SizedBox(height: 32),

            // Submit Button
            FilledButton(
              onPressed: _isLoading ? null : _handleSubmit,
              child: _isLoading
                ? const SizedBox(
                    height: 20,
                    width: 20,
                    child: CircularProgressIndicator(strokeWidth: 2),
                  )
                : Text(isEditing ? 'Update Organisation' : 'Create Organisation'),
            ),
          ],
        ),
      ),
    );
  }
}
