import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:image_picker/image_picker.dart';
import '../../../data/models/organisation.dart';
import '../../../providers/auth_providers.dart';
import '../../../providers/organisation_providers.dart';
import '../../../providers/repository_providers.dart';
import '../../widgets/common/loading_error_widgets.dart';

/// Form for creating/editing organisations
class OrganisationFormScreen extends ConsumerStatefulWidget {
  final String? organisationId;

  const OrganisationFormScreen({
    super.key,
    this.organisationId,
  });

  @override
  ConsumerState<OrganisationFormScreen> createState() => _OrganisationFormScreenState();
}

class _OrganisationFormScreenState extends ConsumerState<OrganisationFormScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  
  bool _isLoading = false;
  bool _isInitialized = false;
  
  // Image picker state
  File? _selectedImage;
  String? _existingLogoUrl;
  bool _isUploadingImage = false;

  bool get isEditing => widget.organisationId != null;

  @override
  void dispose() {
    _nameController.dispose();
    super.dispose();
  }

  void _initializeForm(Organisation org) {
    if (_isInitialized) return;
    _nameController.text = org.name;
    _existingLogoUrl = org.logoUrl;
    _isInitialized = true;
  }

  Future<void> _pickImage() async {
    final picker = ImagePicker();
    
    // Show bottom sheet to choose camera or gallery
    final source = await showModalBottomSheet<ImageSource>(
      context: context,
      builder: (context) => SafeArea(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            ListTile(
              leading: const Icon(Icons.photo_library),
              title: const Text('Choose from Gallery'),
              onTap: () => Navigator.pop(context, ImageSource.gallery),
            ),
            ListTile(
              leading: const Icon(Icons.camera_alt),
              title: const Text('Take a Photo'),
              onTap: () => Navigator.pop(context, ImageSource.camera),
            ),
          ],
        ),
      ),
    );

    if (source == null) return;

    try {
      final pickedFile = await picker.pickImage(
        source: source,
        maxWidth: 512,
        maxHeight: 512,
        imageQuality: 85,
      );

      if (pickedFile != null) {
        setState(() {
          _selectedImage = File(pickedFile.path);
        });
      }
    } catch (e) {
      debugPrint('Error picking image: $e');
    }
  }

  void _removeImage() {
    setState(() {
      _selectedImage = null;
      _existingLogoUrl = null;
    });
  }

  Future<String?> _uploadImageIfNeeded(String orgId) async {
    if (_selectedImage == null) {
      // No new image selected, return existing URL (or null if removed)
      return _existingLogoUrl;
    }

    setState(() => _isUploadingImage = true);

    try {
      final storageService = ref.read(storageServiceProvider);
      final url = await storageService.uploadOrganisationLogo(
        orgId: orgId,
        imageFile: _selectedImage!,
      );
      return url;
    } catch (e) {
      debugPrint('Error uploading image: $e');
      return _existingLogoUrl; // Fallback to existing
    } finally {
      setState(() => _isUploadingImage = false);
    }
  }

  Future<void> _handleSubmit() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isLoading = true);

    try {
      final authState = ref.read(authNotifierProvider);
      final user = authState.value;
      
      if (user == null) {
        throw Exception('User not authenticated');
      }

      if (isEditing) {
        final existing = ref.read(organisationByIdProvider(widget.organisationId!)).value;
        if (existing == null) throw Exception('Organisation not found');

        // Upload image first (if any)
        final logoUrl = await _uploadImageIfNeeded(existing.id);

        final updated = existing.copyWith(
          name: _nameController.text.trim(),
          logoUrl: logoUrl,
        );
        await ref.read(updateOrganisationProvider(updated).future);
      } else {
        // For new organisations, we need to create first then upload
        // Create with temporary null logo
        final newOrg = Organisation(
          id: '', // Will be generated by Supabase
          name: _nameController.text.trim(),
          ownerId: user.id,
          ownerEmail: user.email,
          logoUrl: null, // Will update after upload
          createdAt: DateTime.now(),
          updatedAt: DateTime.now(),
        );
        
        final created = await ref.read(createOrganisationProvider(newOrg).future);
        
        // Now upload image if selected
        if (_selectedImage != null) {
          final logoUrl = await _uploadImageIfNeeded(created.id);
          if (logoUrl != null) {
            final updated = created.copyWith(logoUrl: logoUrl);
            await ref.read(updateOrganisationProvider(updated).future);
          }
        }
      }

      if (mounted) {
        context.go('/admin');
      }
    } catch (e) {
      debugPrint('Error saving organisation: $e');
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  Future<void> _handleDelete() async {
    final confirmed = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Delete Organisation'),
        content: const Text(
          'Are you sure you want to delete this organisation? '
          'This will also delete all associated tournaments, teams, and matches.',
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context, false),
            child: const Text('Cancel'),
          ),
          FilledButton(
            onPressed: () => Navigator.pop(context, true),
            style: FilledButton.styleFrom(
              backgroundColor: Theme.of(context).colorScheme.error,
            ),
            child: const Text('Delete'),
          ),
        ],
      ),
    );

    if (confirmed != true || !mounted) return;

    setState(() => _isLoading = true);

    try {
      // Delete logo from storage first
      final storageService = ref.read(storageServiceProvider);
      await storageService.deleteOrganisationLogo(widget.organisationId!);
      
      await ref.read(deleteOrganisationProvider(widget.organisationId!).future);
      if (mounted) {
        context.go('/admin');
      }
    } catch (e) {
      debugPrint('Error deleting organisation: $e');
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(isEditing ? 'Edit Organisation' : 'New Organisation'),
        leading: IconButton(
          icon: const Icon(Icons.close),
          onPressed: () => context.go('/admin'),
        ),
        actions: [
          if (isEditing)
            IconButton(
              icon: const Icon(Icons.delete),
              tooltip: 'Delete',
              onPressed: _isLoading ? null : _handleDelete,
            ),
        ],
      ),
      body: isEditing
        ? _buildEditingForm()
        : _buildForm(),
    );
  }

  Widget _buildEditingForm() {
    final orgAsync = ref.watch(organisationByIdProvider(widget.organisationId!));

    return orgAsync.when(
      data: (org) {
        if (org == null) {
          return const Center(child: Text('Organisation not found'));
        }
        _initializeForm(org);
        return _buildForm();
      },
      loading: () => const LoadingWidget(),
      error: (e, _) => AppErrorWidget(
        message: e.toString(),
        onRetry: () => ref.invalidate(organisationByIdProvider(widget.organisationId!)),
      ),
    );
  }

  Widget _buildForm() {
    final theme = Theme.of(context);
    
    return SingleChildScrollView(
      padding: const EdgeInsets.all(24),
      child: Form(
        key: _formKey,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            // Name Field (first)
            TextFormField(
              controller: _nameController,
              enabled: !_isLoading,
              textInputAction: TextInputAction.done,
              decoration: const InputDecoration(
                labelText: 'Organisation Name *',
                hintText: 'e.g., Ramadan Football League',
                prefixIcon: Icon(Icons.business),
              ),
              validator: (value) {
                if (value == null || value.trim().isEmpty) {
                  return 'Please enter an organisation name';
                }
                return null;
              },
            ),
            const SizedBox(height: 24),

            // Logo Upload Section
            _buildLogoSection(theme),
            const SizedBox(height: 32),

            // Submit Button
            FilledButton(
              onPressed: _isLoading ? null : _handleSubmit,
              child: _isLoading
                ? const SizedBox(
                    height: 20,
                    width: 20,
                    child: CircularProgressIndicator(strokeWidth: 2),
                  )
                : Text(isEditing ? 'Update Organisation' : 'Create Organisation'),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildLogoSection(ThemeData theme) {
    final hasImage = _selectedImage != null || _existingLogoUrl != null;
    
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          'Organisation Logo',
          style: theme.textTheme.titleMedium,
        ),
        const SizedBox(height: 12),
        
        // Logo preview/upload area
        GestureDetector(
          onTap: _isLoading ? null : _pickImage,
          child: Container(
            height: 150,
            decoration: BoxDecoration(
              color: theme.colorScheme.surfaceContainerHighest,
              borderRadius: BorderRadius.circular(12),
              border: Border.all(
                color: theme.colorScheme.outline.withValues(alpha: 0.3),
                width: 1,
              ),
            ),
            child: _isUploadingImage
                ? const Center(
                    child: Column(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        CircularProgressIndicator(),
                        SizedBox(height: 8),
                        Text('Uploading...'),
                      ],
                    ),
                  )
                : hasImage
                    ? _buildImagePreview(theme)
                    : _buildUploadPlaceholder(theme),
          ),
        ),
        
        // Remove button
        if (hasImage && !_isLoading)
          Padding(
            padding: const EdgeInsets.only(top: 8),
            child: TextButton.icon(
              onPressed: _removeImage,
              icon: const Icon(Icons.delete_outline, size: 18),
              label: const Text('Remove Logo'),
              style: TextButton.styleFrom(
                foregroundColor: theme.colorScheme.error,
              ),
            ),
          ),
      ],
    );
  }

  Widget _buildImagePreview(ThemeData theme) {
    return ClipRRect(
      borderRadius: BorderRadius.circular(12),
      child: Stack(
        fit: StackFit.expand,
        children: [
          if (_selectedImage != null)
            Image.file(
              _selectedImage!,
              fit: BoxFit.cover,
            )
          else if (_existingLogoUrl != null)
            Image.network(
              _existingLogoUrl!,
              fit: BoxFit.cover,
              errorBuilder: (context, error, stackTrace) {
                return _buildUploadPlaceholder(theme);
              },
            ),
          // Tap to change overlay
          Positioned(
            bottom: 0,
            left: 0,
            right: 0,
            child: Container(
              padding: const EdgeInsets.symmetric(vertical: 8),
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  begin: Alignment.bottomCenter,
                  end: Alignment.topCenter,
                  colors: [
                    Colors.black.withValues(alpha: 0.7),
                    Colors.transparent,
                  ],
                ),
              ),
              child: const Text(
                'Tap to change',
                textAlign: TextAlign.center,
                style: TextStyle(
                  color: Colors.white,
                  fontSize: 12,
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildUploadPlaceholder(ThemeData theme) {
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        Icon(
          Icons.add_photo_alternate_outlined,
          size: 48,
          color: theme.colorScheme.primary,
        ),
        const SizedBox(height: 8),
        Text(
          'Tap to upload logo',
          style: theme.textTheme.bodyMedium?.copyWith(
            color: theme.colorScheme.primary,
            fontWeight: FontWeight.bold,
          ),
        ),
        const SizedBox(height: 4),
        Text(
          'PNG or JPG (Max 2MB)',
          style: theme.textTheme.labelSmall?.copyWith(
            color: theme.colorScheme.outline,
          ),
        ),
      ],
    );
  }
}
