import 'package:equatable/equatable.dart';
import 'package:json_annotation/json_annotation.dart';
import '../../core/constants/enums.dart';

part 'organisation.g.dart';

/// Organisation model representing a tournament organising entity
/// 
/// Example: "Al Falaki Ramadan 2026" or "El Maadi Sports Club"
@JsonSerializable(explicitToJson: true)
class Organisation extends Equatable {
  final String id;
  final String name;
  
  @JsonKey(name: 'owner_id')
  final String ownerId;
  
  @JsonKey(name: 'owner_email')
  final String ownerEmail;
  
  final String? description;
  
  @JsonKey(name: 'logo_url')
  final String? logoUrl;
  
  @JsonKey(fromJson: _visibilityFromJson, toJson: _visibilityToJson)
  final Visibility visibility;
  
  @JsonKey(name: 'created_at')
  final DateTime? createdAt;
  
  @JsonKey(name: 'updated_at')
  final DateTime? updatedAt;

  const Organisation({
    required this.id,
    required this.name,
    required this.ownerId,
    required this.ownerEmail,
    this.description,
    this.logoUrl,
    this.visibility = Visibility.public,
    this.createdAt,
    this.updatedAt,
  });

  factory Organisation.fromJson(Map<String, dynamic> json) =>
      _$OrganisationFromJson(json);

  Map<String, dynamic> toJson() => _$OrganisationToJson(this);

  /// Create for new organisation (without ID, will be generated by DB)
  Map<String, dynamic> toInsertJson() => {
    'name': name,
    'owner_id': ownerId,
    'owner_email': ownerEmail,
    'description': description,
    'logo_url': logoUrl,
    'visibility': visibility.name,
  };

  Organisation copyWith({
    String? id,
    String? name,
    String? ownerId,
    String? ownerEmail,
    String? description,
    String? logoUrl,
    Visibility? visibility,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return Organisation(
      id: id ?? this.id,
      name: name ?? this.name,
      ownerId: ownerId ?? this.ownerId,
      ownerEmail: ownerEmail ?? this.ownerEmail,
      description: description ?? this.description,
      logoUrl: logoUrl ?? this.logoUrl,
      visibility: visibility ?? this.visibility,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  @override
  List<Object?> get props => [
    id, name, ownerId, ownerEmail, description, 
    logoUrl, visibility, createdAt, updatedAt
  ];
}

Visibility _visibilityFromJson(String value) => Visibility.fromString(value);
String _visibilityToJson(Visibility visibility) => visibility.name;
